<html>
<head>
<?php include('header.php');?>
<div class="span"  id="span">

<a href="login.php"><label style="background:#30a4ffd1;" class ="bk" ><i class="fa fa-user"></i>&nbsp;Login</label></a>
</div>

</head>
<style>
.bk{
float:right;	
 font-size: 2rem;
 color:white;
 border-radius:7px;
 padding:3px;
 cursor:pointer;
}
.bk:hover{
	font-size: 2.2rem;
}
span {
	
	color:deepskyblue;
	
}
#span{
	 display:fixed;
 }
 .span{
	 
	    display: inline-block;
    position: relative;
    background-color: #1b9bff;
    font-size: 1.2rem;
    color: white;
    padding: 5px;
    justify-content: center;
    align-items: center;
   
    padding-right: 20px;
    padding-bottom: 2%;
    letter-spacing: 2px;
    width: 100%;
    height: 40px;
}
input[type="button"]:hover:not(.active) {
	background-color: #ddd;
}
 input[type="button"] {
	transition: all .3s;
    border: 1px solid #ddd;
    padding: 8px 16px;
    text-decoration: none;
    border-radius: 5px;
	 
}
 tr:hover:not(th) {background-color: rgba(237,35,64,.1);}
 table {
  color: #333;
  
  
   
  border-collapse: separate;
   
  border: 2px solid #1b9bff;
  
  margin: 50px auto;
  box-shadow: 0 4px 8px 0 rgba(0,0,0,.16);
  border-radius: 2px;
}
 th {
  background: #0b72c2;
  color: #fff;
  border: none;
  padding:15px;
}
td{
	 padding:10px;
	 border: none;
	 
}
 
 
 
table{
	
}
h3{
	font-size:17px;
}
tr{
	
}
td{
	
}
h1{
	color:deepskyblue;
}
h3{
	color:deepskyblue;
}
</style>
<body>
<table border="1">
<tr><center style="font-size:33px;">Transport Tarif</center></tr>
<tr><th>Village</th><th>Transport Cost</th></tr>
<tr><td>BAHIR DAR(DIBZA) </td><td>&nbsp;&nbsp;&nbsp;10 </td></tr>
<tr><td>STADIYEM(ABMA) </td><td>&nbsp;&nbsp;&nbsp;5 </td></tr>
<tr><td>ADDIS ABEBA(SHEWA BER) </td><td>&nbsp;&nbsp;&nbsp;15 </td></tr>
<tr><td>HOSPITAL </td><td>&nbsp;&nbsp;&nbsp;5 </td></tr>
<tr><td>UNIVERSITY </td><td>&nbsp;&nbsp;&nbsp;5 </td></tr></table>

</table>
<table border="1">
<tr><center style="font-size:33px;">Common Medical Abbreviations</center></tr>
<tr><th>Abbreviation</th><th> Intended Meaning</th><th>Notes About Confusion</th></tr>
<tr><td>1/2NS </td><td>one-half normal saline (0.45%) </td><td>Normal saline (NS) is 0.9%, so one-half normal saline is 0.45% </td></tr>
<tr><td>5-ASA </td><td>5-aminosalicylic acid </td><td>	
Can be misinterpreted as five tablets of aspirin (per FDA).Spell out full drug name. </td></tr>
<tr><td>a </td><td>before </td><td> </td></tr>
<tr><td>A.M. </td><td>morning </td><td> </td></tr>
<tr><td>aa </td><td> of each</td><td> </td></tr>
<tr><td>AAA </td><td>abdominal aortic aneurysm (called a "triple-A") </td><td>Can be misinterpreted as 'apply to affected area' </td></tr>
<tr><td>AAA </td><td>apply to affected area </td><td>Can be misinterpreted as 'abdominal aortic aneurysm' </td></tr>
<tr><td>ac </td><td>before meals </td><td> </td></tr>
<tr><td>achs </td><td>before meals and at bedtime </td><td> </td></tr>
<tr><td>AD </td><td>	right ear </td><td> </td></tr>
<tr><td>ad lib </td><td>freely; as much as desired </td><td>to saturation </td></tr>
<tr><td>ad sat. </td><td> to saturation</td><td> </td></tr>
<tr><td>ad. </td><td>to; up to </td><td>Caution not to confuse with AD (meaning right ear) </td></tr>
<tr><td>ALT </td><td>alanine aminotransferase </td><td> </td></tr>
<tr><td>ASA </td><td>aspirin </td><td>Spell out drug name "aspirin" </td></tr>
</table>
<div style="margin-left:25px;margin-right:30%"> 
<div>
<h1>Is it safe to take expired medications?</h1>

<div style="font-size:22px;">The U.S. Food and Drug Administration (FDA) recommends never taking drugs beyond their expiration 
date as it is risky with many unknown variables. For example, how your drug is stored before you receive it, 
chemical make-up, and original manufacturing date can all affect potency of a drug.

In 1963, a report was published that tied degraded tetracycline use 
with a form of renal tubular (kidney) damage known as "Fanconi Syndrome". However,
that formulation of tetracycline is no longer marketed in the U.S.1, 11, and many medical 
experts question the results of this case report.

Solid dosage forms, such as tablets and capsules, appear to be most stable past their 
expiration date. Drugs that exist in solution or as a reconstituted suspension, and that
require refrigeration (such as amoxicillin suspension), may not have the required potency 
if used when outdated. Loss of potency can be a major health concern, especially when treating
an infection with an antibiotic. Additionally, antibiotic resistance may occur with sub-potent medications.
</div>
<br>
<div>
<h1>Common Drug Side Effects</h1>
<P></p>
</div>
<div style="font-size:22px;">
Every drug has side effects. How vulnerable you are to these side 
effects depends on many different factors, which can be generally 
grouped as patient-related, drug-related, and environmentally or 
socially-related. Find out if you have any characteristics that 
will increase your 
susceptibility to drug-related reactions, and what you can do to 
manage some of these possible side effects.
Children are not small adults. The way their bodies absorb metabolize 
and eliminate drugs differs from adults, and this is especially true in
babies. Younger children tend to absorb medicine more slowly from the stomach but 
have faster intramuscular (IM) absorption rates. In early life, they have a higher 
body water to lipid ratio and a larger liver to bodyweight ratio. Liver enzymes are 
immature as is their kidney function. In addition, the permeability of their blood-brain barrier 
(the layer of cells that restricts the passage of substances from the bloodstream to the brain) is higher.
</div><br><div>
<h1>Top 6 Safety Tips for Stopping Your Meds</h1>
 <h3>1,Talk to Your Doctor First</h3>
 <div style="font-size:22px;">
Many factors need to be considered before you stop any medication that has been
prescribed for you, that’s why it is so important to talk to your doctor first. </div><br>
<h3>2,Discuss Your Medications With Your Doctor</h3>
<div style="font-size:22px;">Roughly 40 percent of people over the age of 60 take at least five prescription drugs,
including medications they no longer need. Some medications -- like sleeping pills
-- should only be used short-term.</div><br>
<h3>3. Stop for the Right Reason</h3>
<div style="font-size:22px;">According to a report from CVS Caremark, half of patients taking maintenance
medications for chronic conditions will stop taking them within the first year 
of starting therapy. This "non-adherence" (not sticking to your treatment plan)
results in roughly a $300 million charge to health care costs per year. Non-adherence can lead to worsening of 
long-term health conditions, increased hospitalizations, and worse outcomes overall.</div>
<h3>4. Ask Your Doctor How to Best Stop Your Medication.</h3><br>
<div style="font-size:22px;">Some drugs can be stopped immediately without a special discontinuation schedule,
but many medications require a taper, which is a slow reduction in
dose or frequency over a longer period of time. Slow tapers help to
avoid disagreeable side effects or even withdrawals that you might 
experience if you stopped the drug quickly.
If you are stopping several medications, you may want to taper them 
one at a time to avoid added side effects -- always check with your doctor.</div>
<h3>5. Learn Your Medicine Side Effects if You Quickly Stop.</h3><br>
<div style="font-size:22px;">For example, abruptly stopping some selective serotonin reuptake inhibitors (SSRI) 
antidepressants prescribed to boost your mood -- like Paxil (paroxetine) or Zoloft 
(sertraline) -- can lead to a host of disturbing side effects, such as anxiety, dizziness, 
upset stomach, or fatigue. This is called antidepressant discontinuation syndrome. 
Not everyone experiences this antidepressant discontinuation syndrome, only about 1 
in 5 people. It is not usually dangerous, and typically subsides in a few days depending 
upon your drug, but there are ways to lessen its effect.

Antidepressant discontinuation syndrome may be more </div><br>
<h3>6. Chart Your Discontinuation Plan</h3>
<div style="font-size:22px;">If you are started on a new medication, you should ask several 
questions of your doctor and record the responses for future reference, including:

Your dose and schedule
Your expected outcomes
Common side effects, including if the drug is abruptly stopped
Cost of your drug and generic availability
How long are you are going to take the medication?</div>
 
</div>
<br>
<div>
<h1>Ways to Prevent a Deadly Drug Interaction</h1><br>
<h3>Communicate Frequently</h3>
<div style="font-size:22px;">Tell your pharmacist each time you start or stop a medication, 
including any over-the-counter (OTC) drug, herbal supplement, 
or vitamin. Keep an updated list of meds, including nonprescription drugs
-- and share with your health care providers, including your doctor, pharmacist, 
and dentist, anytime you start or stop a medication.</div>
<h3>Research Your Medicine Yourself </h3><br>
<div style="font-size:22px;">Use a reliable and consumer-friendly online drug interaction tool like the Drugs.com 
Interaction Checker to become engaged in your health and learn about your medications. 
If you need help understanding the information, be sure to call your pharmacist. Always 
check for drug interactions even when you purchase OTC medications, herbal supplements or vitamins.</div>
<h3>Keep All of Your Prescriptions at One Pharmacy </h3><br>
<div style="font-size:22px;">By keeping all of your prescriptions at one pharmacy, a regular drug review 
and drug interaction screen can be done electronically that incorporates all 
of your medicines. Talk with your pharmacist and doctor and communicate new and 
discontinued medications with all of your health care providers.
Communication is key to preventing drug interactions.</div>

 
</div>
<br><br>
<div>
<h1>Pros and Cons of Prescription Medicine</h1>
 <div style="font-size:22px;"> If the FDA considers a medication safe enough to approve,
that means its benefits outweigh its known risks. The medications 
you take play an important role in your overall health. However, all 
medications have side effects, warnings and drug interactions, so it's
important to understand your treatments,
expected results, and alternative medical options. </div>
</div><br><br>
</div></div> 
<h5 style="float:left;"><i style="font-size:15px;">Further information:<a href="www.drugs.com">www.drugs.com</a></i></h5>
</body>
<footer>
<?php include('footer.php');  ?>
</footer>
</html>